export const licenses = [
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "@azure/msal-browser",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/AzureAD/microsoft-authentication-library-for-js.git",
    "remoteVersion": "2.38.1",
    "installedVersion": "2.38.0",
    "definedVersion": "^2.38.0",
    "author": "Microsoft nugetaad@microsoft.com https://www.microsoft.com"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "@azure/msal-react",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/AzureAD/microsoft-authentication-library-for-js.git",
    "remoteVersion": "1.5.10",
    "installedVersion": "1.5.9",
    "definedVersion": "^1.5.9",
    "author": "Microsoft nugetaad@microsoft.com https://www.microsoft.com"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "@emotion/react",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/emotion-js/emotion.git#main",
    "remoteVersion": "11.11.1",
    "installedVersion": "11.11.1",
    "definedVersion": "^11.11.1",
    "author": "Emotion Contributors"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "@emotion/styled",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/emotion-js/emotion.git#main",
    "remoteVersion": "11.11.0",
    "installedVersion": "11.11.0",
    "definedVersion": "^11.11.0",
    "author": "n/a"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "@fontsource/roboto",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "Apache-2.0",
    "link": "git+https://github.com/fontsource/font-files.git",
    "remoteVersion": "5.0.8",
    "installedVersion": "5.0.5",
    "definedVersion": "^5.0.5",
    "author": "Google Inc."
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "@mui/icons-material",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/mui/material-ui.git",
    "remoteVersion": "5.14.3",
    "installedVersion": "5.14.3",
    "definedVersion": "^5.14.3",
    "author": "MUI Team"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "@mui/material",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/mui/material-ui.git",
    "remoteVersion": "5.14.4",
    "installedVersion": "5.14.3",
    "definedVersion": "^5.14.3",
    "author": "MUI Team"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "buffer",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git://github.com/feross/buffer.git",
    "remoteVersion": "6.0.3",
    "installedVersion": "6.0.3",
    "definedVersion": "^6.0.3",
    "author": "Feross Aboukhadijeh feross@feross.org https://feross.org"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "extract-colors",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "GPL-3.0",
    "link": "git+https://github.com/Namide/extract-colors.git",
    "remoteVersion": "3.0.0",
    "installedVersion": "3.0.0",
    "definedVersion": "^3.0.0",
    "author": "damien@doussaud.fr"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "i18next",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/i18next/i18next.git",
    "remoteVersion": "23.4.4",
    "installedVersion": "23.4.1",
    "definedVersion": "^23.4.1",
    "author": "Jan Mühlemann <jan.muehlemann@gmail.com> (https://github.com/jamuhl)"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "i18next-browser-languagedetector",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/i18next/i18next-browser-languageDetector.git",
    "remoteVersion": "7.1.0",
    "installedVersion": "7.1.0",
    "definedVersion": "^7.1.0",
    "author": "Jan Mühlemann <jan.muehlemann@gmail.com> (https://github.com/jamuhl)"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "music-metadata-browser",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/Borewit/music-metadata-browser.git",
    "remoteVersion": "2.5.10",
    "installedVersion": "2.5.10",
    "definedVersion": "^2.5.10",
    "author": "Borewit https://github.com/Borewit"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "react",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/facebook/react.git",
    "remoteVersion": "18.2.0",
    "installedVersion": "18.2.0",
    "definedVersion": "^18.2.0",
    "author": "n/a"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "react-dom",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/facebook/react.git",
    "remoteVersion": "18.2.0",
    "installedVersion": "18.2.0",
    "definedVersion": "^18.2.0",
    "author": "n/a"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "react-i18next",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/i18next/react-i18next.git",
    "remoteVersion": "13.1.2",
    "installedVersion": "13.0.3",
    "definedVersion": "^13.0.3",
    "author": "Jan Mühlemann <jan.muehlemann@gmail.com> (https://github.com/jamuhl)"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "react-router-dom",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/remix-run/react-router.git",
    "remoteVersion": "6.15.0",
    "installedVersion": "6.14.2",
    "definedVersion": "^6.14.2",
    "author": "Remix Software <hello@remix.run>"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "short-uuid",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/oculus42/short-uuid.git",
    "remoteVersion": "4.2.2",
    "installedVersion": "4.2.2",
    "definedVersion": "^4.2.2",
    "author": "Samuel Rouse"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "swr",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/vercel/swr.git",
    "remoteVersion": "2.2.1",
    "installedVersion": "2.2.0",
    "definedVersion": "^2.2.0",
    "author": "n/a"
  },
  {
    "department": "kessler",
    "relatedTo": "stuff",
    "name": "zustand",
    "licensePeriod": "perpetual",
    "material": "material",
    "licenseType": "MIT",
    "link": "git+https://github.com/pmndrs/zustand.git",
    "remoteVersion": "4.4.1",
    "installedVersion": "4.4.0",
    "definedVersion": "^4.4.0",
    "author": "Paul Henschel"
  }
]